# Generated by Django 3.1.4 on 2020-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genderno', models.IntegerField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='clothes',
            new_name='cloth',
        ),
    ]
