# Generated by Django 3.1.4 on 2020-12-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='brand',
            field=models.CharField(default='benson', max_length=20),
        ),
        migrations.AddField(
            model_name='watches',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
