# Generated by Django 3.1.4 on 2020-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20201212_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='brand',
            field=models.CharField(default='khadi', max_length=20),
        ),
        migrations.AddField(
            model_name='cloth',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
