# Generated by Django 3.1.4 on 2020-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20201212_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='brand',
            field=models.CharField(default='J.', max_length=20),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
