# Generated by Django 3.1.4 on 2020-12-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_auto_20201212_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='brand',
            field=models.CharField(default='Dior', max_length=20),
        ),
        migrations.AddField(
            model_name='perfumes',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
